#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

runcmd:
  - systemctl enable docker
  - service docker start
  - usermod -a -G docker ec2-user
  - chown 1001:1001 /data
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release setup psmdb-42
  - percona-release setup -y pmm2-client
  - yum -y install percona-server-mongodb pmm2-client
  - systemctl enable mongod
  - systemctl start mongod
  - systemctl status mongod
  - pmm-admin config --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
