apiVersion: v1
kind: Secret
metadata:
  name: psmdb-60-cluster-secrets
  namespace: percona-server-mongodb-60
type: Opaque
stringData:
  PMM_PASSWORD: "changeme"
  PERCONAADMIN_PASSWORD: "changeme"
  YCSB_PASSWORD: "changeme"
  MONGO_KEY: "changeme"
