secrets:
  users:
    pmm: "PMM_PASSWORD"
    perconaadmin: "PERCONAADMIN_PASSWORD"
    ycsb: "YCSB_PASSWORD"
  key: "MONGO_KEY"

sharding:
  enabled: true
  configsvr:
    size: 3
    resources:
      requests:
        memory: "1G"
        cpu: "500m"
      limits:
        memory: "2G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: "10Gi"
  shards:
    size: 3
    resources:
      requests:
        memory: "1G"
        cpu: "500m"
      limits:
        memory: "2G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: "10Gi"
  mongos:
    size: 1
    resources:
      requests:
        memory: "1G"
        cpu: "500m"
      limits:
        memory: "2G"
        cpu: "1"

pmm:
  enabled: true
  serverHost: 'pmm-server'
  serverUser: 'admin'
