#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

bootcmd:
  - while [[ ! -b $(readlink -f /dev/nvme1n1) ]]; do echo "waiting for the disk..."; sleep 5; done
  - mkfs.xfs -L data /dev/nvme1n1
  - mkdir -p /data

mounts:
  - ["/dev/nvme1n1", "/data", "xfs", "defaults,nofail,noatime", "0", "2"]

packages:
  - curl
  - jq

runcmd:
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install consul
  - usermod -d /opt/consul consul
  - systemctl enable consul
  - systemctl start consul
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release setup -y psmdb-60
  - yum -y install percona-server-mongodb
  - percona-release setup -y pmm2-client
  - yum -y install pmm2-client
  - chown mongod:mongod /data/ /etc/mongo-key
  - chmod 600 /etc/mongo-key
  - systemctl enable mongod
  - systemctl start mongod
  - timeout 120 bash -c 'until curl --request 'GET' --insecure https://${pmm_server_endpoint}/v1/readyz ; do sleep 3; done'
  - bash pip3 install ansi2txt
  - bash /tmp/mongodb-init-rs.sh
  - pmm-admin config --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - pmm-admin add mongodb --port 27019 --username=pmm --password='${mongodb_60_pmm_user_password}' --cluster='mdb60-cluster' --replication-set='mongo-60-rs-${shard_number}' --environment='prod' --service-name=${name} --enable-all-collectors

write_files:

  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "proxysql"]
      server = false

  - path: /etc/consul.d/mongod-service.json
    permissions: "0644"
    content: |
      {
        "services": [
          {
            "name": "mongo-60-${replica_set_name}",
            "tags": ["mongo-60-rs-${shard_number}", "${name}"],
            "address": "",
            "port": 27019,
            "checks": [
              {
                "args": ["mongosh", "--port", "27019", "--eval", "db.runCommand(\"ping\").ok", "-quiet"],
                "interval": "10s"
              }
            ]
          },
          {
            "name": "mongo-60-rs-${shard_number}-primary",
            "checks": [{
              "args": ["/usr/local/bin/mongo_is_primary.sh"],
              "interval": "10s"
            }]
          }        ]
      }

  - path: /usr/local/bin/mongo_is_primary.sh
    permissions: "0700"
    content: |
        #!/bin/bash
        masterstat=$(NO_COLOR=1 /bin/mongosh --port 27019 -u pmm -p ${mongodb_60_pmm_user_password} --quiet --eval 'd=db.isMaster();EJSON.stringify(d.ismaster+"#"+d.primary)' | /usr/local/bin/ansi2txt)
        primary=$(echo $masterstat | cut -d# -f2)
        primary=${primary:0:-1}
        ismaster=$(echo $masterstat | cut -d# -f1)
        echo "$primary is primary"
        if [[ "${ismaster:1}" =~ "true" ]]; then
          exit 0
        else
          exit 2
        fi

  - path: /etc/mongosh.conf
    content: |
      enableTelemetry: false

  - path: /etc/mongod.conf
    content: |
      sharding:
        clusterRole: shardsvr

      replication:
        replSetName: ${replica_set_name}

      storage:
        dbPath: /data
        journal:
          enabled: true

      systemLog:
        destination: file
        logAppend: true
        path: /var/log/mongo/mongod.log

      setParameter:
        logLevel: 0        

      processManagement:
        fork: true
        pidFilePath: /var/run/mongod.pid

      net:
        port: 27019
        bindIp: 0.0.0.0

      operationProfiling:
        mode: all
        slowOpThresholdMs: 200
        rateLimit: 100

      security:
        keyFile: /etc/mongo-key

  - path: /etc/mongo-key
    content: |
      ${mongodb_60_keyfile}

  - path: /tmp/init.js
    content: |
      db.getMongo().setReadPref("primaryPreferred")
      rs.initiate({
        _id: "${replica_set_name}",
        members: [
          { _id : 0, host : "mongo-60-rs-${shard_number}-0.${route53_name}:27019", priority: 2 },
          { _id : 1, host : "mongo-60-rs-${shard_number}-1.${route53_name}:27019", priority: 1 },
          { _id : 2, host : "mongo-60-rs-${shard_number}-2.${route53_name}:27019", priority: 1 }
        ]
      })

  - path: /tmp/admin.js
    content: |
      admin = db.getSiblingDB("admin")
      admin.createUser({
        user: "pmm-admin",
        pwd: "${mongodb_60_pmm_admin_password}",
        roles: [
            { role: "userAdminAnyDatabase", db: "admin" },
            { role: "clusterAdmin", db: "admin" }
        ]
      })

  - path: /tmp/users.js
    content: |
      db.getSiblingDB("admin").createRole({
          role: "explainRole",
          privileges: [{
            resource: { db: '', collection: '' },
            actions: [
              'collStats',
              'dbHash',
              'dbStats',
              'find',
              'listCollections',
              'listIndexes'
            ]
          },
          {
            resource: { db: '', collection: 'system.profile' },
            actions: [ 'collStats', 'dbStats', 'indexStats' ]
          }],
          roles:[]
      })
      db.getSiblingDB("admin").createUser({
        user: "pmm",
        pwd: "${mongodb_60_pmm_user_password}",
        roles: [
            { role: "explainRole", db: "admin" },
            { role: "clusterMonitor", db: "admin" },
            { role: "read", db: "local" }
        ]
      })
      db.getSiblingDB("admin").createUser({
        user: "ycsb",
        pwd: "${mongodb_ycsb_password}",
        roles: [
            { role: "readWrite", db: "ycsb" }
        ]
      })

  - path: /tmp/mongodb-init-rs.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      
      myhostname=$(hostname -f)
      memberid=$(hostname -f | cut -d. -f1 | cut -d'-' -f5)
      
      echo "-- MongoDB RS"
      echo "--- $${myhostname}"
      echo "--- This is member id $${memberid}"
      
      # Wait for mongods
      echo "-- Waiting for all 3 members..."
      
      for (( i=1 ; i<=100 ; i++ )); do
        num=$(curl -s http://pmm-server:8500/v1/health/checks/mongo-60-rs-${shard_number} | jq -r '[.[]|select(.Status=="passing")]|length')
        if [ $num -eq 3 ]; then
          echo "-- Looks like all 3 members are online"
          break
        fi
        
        echo "-- Only $${num} members in consul; retry $${i}/100"
        sleep 2
      done
      
      # We pick rs-[01]-0 to be primary. Run the init only on the primary
      if [ "$${memberid}" == "0" ]; then
        echo "-- We are shard 0; run init"
        mongosh --port 27019 /tmp/init.js
      else
        echo "-- We are NOT shard 0; We will wait"
      fi
      
      # Wait for replicaset to have 3 members
      # Get the replicaset status. Loop through all members adding up their 'health' value (1 or 0).
      # If all 3 servers are online, health should = 3. If it doesn't, sleep and try again

      for (( i=1 ; i<=100 ; i++ )); do
        health=$(mongosh --port 27019 -quiet --eval "var m=db.adminCommand({replSetGetStatus:1}).members; var s=0; m.forEach(function(a){ s+=a.health; }); print(s);")
        if [ $? -eq 0 ]; then
          if [ $health -eq 3 ]; then
            echo "-- Found 3 healthy members of replicaset"
            sleep 2
            break
          fi
        fi
        echo "-- Waiting on replicaset members, retry $${i}/100"
        sleep 2
      done
      
      # Print report to cloud log
      echo "-- ReplicaSet Members:"
      mongosh --port 27019 -quiet --eval "var m=db.adminCommand({replSetGetStatus:1}).members; m.forEach(function(a){ print(a.stateStr+':'+a.name); });"
      
      # Determine/wait for primary
      for (( i=1 ; i<=100 ; i++ )); do
        primary=$(mongosh --port 27019 --eval 'rs.isMaster().primary' -quiet | cut -d: -f1)
        if [ "$${primary:0:5}" == "mongo" ]; then
          echo "-- $${primary} is PRIMARY, we are $${myhostname}"
          sleep 2
          break
        fi
        echo "-- Waiting on a primary, retry $${i}/100"
        sleep 2
      done
      
      # Is this host PRIMARY? If so, create the pmm-admin user and pmm user
      if [ "$${myhostname}" == "$${primary}" ]; then
        echo "-- We are PRIMARY!"
        mongosh --port 27019 /tmp/admin.js
        sleep 2
        mongosh --port 27019 -u pmm-admin -p '${mongodb_60_pmm_admin_password}' /tmp/users.js
      else
        echo "-- We are NOT primary, waiting for auth"
        # Since we are not primary, we need to wait until the primary has replicated
        # the PMM user to us, otherwise pmm add mongo will fail
        
        for (( i=1 ; i<=100 ; i++ )); do
          # This will fail until auth replicates, so we keep running the ping with auth until it no longer fails
          ret=$(mongosh --port 27019 -quiet --eval 'db.runCommand("ping").ok' -u pmm-admin -p "${mongodb_60_pmm_admin_password}" 2>&1 >/dev/null)
          if [ $? -eq 0 ]; then
            echo "-- Auth is enabled"
            break
          fi
          echo "-- Waiting on auth, retry $${i}/100"
          sleep 2
        done
      fi
