apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:7.2.6
          ports:
          - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: valkey
