apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raw-manifests
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: valkey
        namespace: "valkey"
        repoURL: https://github.com/percona/pmm-infra.git
        targetRevision: gitops
        path: "apps/databases/instances/valkey"
  template:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
