apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ps-84-replication
        namespace: "percona-server-mysql-84"
        chart: ps-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 1.0.0
        helm:
          values: |
            secrets:
              users:
                root: "ROOT_PASSWORD"
                xtrabackup: "XTRABACKUP_PASSWORD"
                monitor: "MONITOR_PASSWORD"
                clustercheck: "CLUSTERCHECK_PASSWORD"
                proxyadmin: "PROXYADMIN_PASSWORD"
                pmmserver: "PMMSERVER_PASSWORD"
                sysbench: "SYSBENCH_PASSWORD"
                replica: "REPLICA_PASSWORD"
                proxysql: "PROXYSQL_PASSWORD"
                pmm-admin: "PMM_ADMIN_PASSWORD"
                consul-health-check: "CONSUL_HEALTH_CHECK_PASSWORD"
                sysbench-direct-ps84: "SYSBENCH_DIRECT_PS84_PASSWORD"
                sysbench-proxysql-ps84: "SYSBENCH_PROXYSQL_PS84_PASSWORD"

            mysql:
              image:
                repository: percona/percona-server
                tag: "8.4"
              size: 2
              clusterType: asynchronous
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1"
              volumeSpec:
                persistentVolumeClaim:
                  resources:
                    requests:
                      storage: "10Gi"

            pmm:
              enabled: true
              serverHost: 'pmm-server'
              serverUser: 'admin'

            proxy:
              haproxy:
                enabled: false
              router:
                enabled: false
  template:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: '{{name}}'
          values: '{{helm.values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
