apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ps-80-replication
        namespace: "percona-server-mysql-80"
        chart: ps-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 1.0.0
        valuesFile: apps/databases/instances/ps-80-replication/values.yaml
      - name: ps-84-replication
        namespace: "percona-server-mysql-84"
        chart: ps-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 1.0.0
        valuesFile: apps/databases/instances/ps-84-replication/values.yaml
      - name: pxc-80-cluster
        namespace: "percona-xtradb-cluster-80"
        chart: ps-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 1.0.0
        valuesFile: apps/databases/instances/pxc-80-cluster/values.yaml
      - name: ps-84-gr-cluster
        namespace: "percona-server-mysql-84-gr"
        chart: ps-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 1.0.0
        valuesFile: apps/databases/instances/ps-84-gr-cluster/values.yaml

      - name: pg-16-cluster
        namespace: "percona-postgresql-16"
        chart: pg-db
        repoURL: https://percona.github.io/percona-helm-charts/
        targetRevision: 2.8.0
        valuesFile: apps/databases/instances/pg-16-cluster/values.yaml
  template:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: '{{name}}'
      namespace: argocd
      labels:
        commonLabels: "true" # Placeholder for commonLabels from kustomization.yaml
    spec:
      project: default
      sources:
      - repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        ref: chart-source
      - repoURL: https://github.com/percona/pmm-infra.git
        targetRevision: gitops
        path: apps/databases/instances/{{name}}
        ref: values-source
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      helm:
        valueFiles:
          - $values-source/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true