apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators/postgresql-operator.yaml
  - operators/mysql-operator.yaml
  - operators/mongodb-operator.yaml
  - operators/pxc-operator.yaml
  - clusters-app.yaml
