apiVersion: v1
kind: Secret
metadata:
  name: ps-84-replication-secrets
  namespace: mysql
type: Opaque
stringData:
  ROOT_PASSWORD: "changeme"
  XTRABACKUP_PASSWORD: "changeme"
  MONITOR_PASSWORD: "changeme"
  CLUSTERCHECK_PASSWORD: "changeme"
  PROXYADMIN_PASSWORD: "changeme"
  PMMSERVER_PASSWORD: "changeme"
  SYSBENCH_PASSWORD: "changeme"
  REPLICA_PASSWORD: "changeme"
  PROXYSQL_PASSWORD: "changeme"
  PMM_ADMIN_PASSWORD: "changeme"
  CONSUL_HEALTH_CHECK_PASSWORD: "changeme"
  SYSBENCH_DIRECT_PS84_PASSWORD: "changeme"
  SYSBENCH_PROXYSQL_PS84_PASSWORD: "changeme"
