apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-mongodb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/percona/percona-helm-charts.git
    targetRevision: psmdb-operator-1.21.1
    path: charts/psmdb-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: percona-mongodb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
