apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/percona/percona-helm-charts.git
      targetRevision: ps-operator-1.0.0
      path: charts/ps-operator
      helm:
        valueFiles:
          - mysql-operator/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
