apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-postgresql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: pg-operator
    targetRevision: 2.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: pgo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true