apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-postgresql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/percona/percona-postgresql-operator.git
    targetRevision: v2.8.0
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: pgo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
