apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/v1.18.0/deploy/bundle.yaml

patches:
- path: secret-patch.yaml
  target:
    kind: Secret
    name: my-env-var-secrets