---
# This playbook contains tasks executed for pmmdemo
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Set Google Analytics ID
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: analytics
        option: google_analytics_ua_id
        value: "UA-343802-29"

    - name: Enable anonymous access
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: auth.anonymous
        option: enabled
        value: "true"
