#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

runcmd:
  - yum install haproxy

write_files:
- path: /tmp/haproxy.cfg
  content: |
    global
            log 127.0.0.1   local0
            log 127.0.0.1   local1 notice
            maxconn 4096
            uid 99
            gid 99
            #daemon
            debug
            #quiet

    defaults
            log     global
            mode    http
            option  tcplog
            option  dontlognull
            retries 3
            redispatch
            maxconn 2000
            contimeout      5000
            clitimeout      50000
            srvtimeout      50000

    listen mysql-cluster 0.0.0.0:3306
        mode tcp
        balance roundrobin
        option  httpchk

        server db01 percona-xtradb-cluster-0:3306 check port 9200 inter 12000 rise 3 fall 3
        server db02 percona-xtradb-cluster-1:3306 check port 9200 inter 12000 rise 3 fall 3
        server db03 percona-xtradb-cluster-2:3306 check port 9200 inter 12000 rise 3 fall 3
