#cloud-config
fqdn: ${fqdn}
hostname: ${name}
manage_etc_hosts: true
prefer_fqdn_over_hostname: true
preserve_hostname: false
repo_upgrade: all

packages:
  - bind-utils
  - curl

bootcmd:
  - while [[ ! -b $(readlink -f /dev/nvme1n1) ]]; do echo "waiting for the disk..."; sleep 5; done
  - mkfs.xfs -L data /dev/nvme1n1
  - mkdir -p /data

mounts:
  - ["/dev/nvme1n1", "/data", "xfs", "defaults,noatime", "0", "2"]

runcmd:
  - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - dnf -y install consul
  - systemctl enable consul && systemctl start consul
  - dnf -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release setup -y ps-84-lts
  - PERCONA_TELEMETRY_DISABLE=1 dnf -y install percona-server-server
  - percona-release setup -y pmm3-client
  - dnf -y install pmm-client
  - echo '!includedir /etc/my.cnf.d/' >> /etc/my.cnf
  - chown mysql:mysql /data/
  - semanage fcontext -a -t mysqld_db_t "/data(/.*)?" && restorecon -Rv /data
  - if [ "${name}" == "percona-server-84-1" ]; then mv /tmp/replica-config.cnf /etc/my.cnf.d/; fi
  - systemctl enable mysqld.service
  - systemctl start mysqld.service
  - systemctl status mysqld.service
  - bash /root/init-mysql.sh
  - curl -s https://raw.githubusercontent.com/percona/pmm-infra/pmmdemo/provision_scripts/scripts/waiter.sh -o /usr/local/bin/waiter.sh
  - chmod 0755 /usr/local/bin/waiter.sh
  - bash /usr/local/bin/waiter.sh readyz
  - pmm-admin config --az="us-east-1f" --region="us-east-1" --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - bash /usr/local/bin/waiter.sh mysql
  - pmm-admin add mysql --metrics-mode=push --username=pmm-admin --password='${mysql_root_password}' --cluster='ps-84-cluster' --replication-set='ps-84-cluster' --environment='prod' --query-source=slowlog --service-name="${name}-mysql"
  - dnf -y install https://github.com/ncabatoff/process-exporter/releases/download/v0.8.5/process-exporter_0.8.5_linux_amd64.rpm
  - bash /usr/local/bin/waiter.sh process-exporter
  - pmm-admin add external --group=processes --listen-port=9256 --environment="prod" --service-name="${name}-processes" --cluster="processes-cluster"

write_files:
  - path: /etc/resolv.conf
    permissions: "0644"
    content: |
      ; generated by #cloud-config
      search ${local_domain} ec2.internal
      options timeout:2 attempts:5
      nameserver 10.0.0.2
  - path: /usr/local/bin/consul-check-mysql.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      # Set MySQL server credentials
      MYSQL_USER="consul-health-check"
      MYSQL_PASSWORD="${mysql_root_password}"
      MYSQL_SOCKET="/var/lib/mysql/mysql.sock"
      while true ; do
        # Attempt to connect using MySQL Shell with a 2-second timeout
        mysql --socket="$MYSQL_SOCKET" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --connect-timeout=2 -e "SELECT 1"
        # Check the exit status of mysqlsh to determine connection success
        if [[ $? -eq 0 ]]; then
          echo "Successfully connected to MySQL service."
          exit 0
        else
          echo -n "Connection attempt to MySQL service failed. Sleeping 1 second... "
          date
          sleep 1
        fi
      done
  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "bastion"]
      server = false
      ui_config{
        enabled = true
      }
  - path: /etc/consul.d/percona-server-84-service.json
    permissions: "0644"
    content: |
      {
        "service": {
          "address": "${fqdn}",
          "id": "percona-server-84",
          "name": "percona-server-84",
          "port": 3306,
          "tags": ["${name}"],
          "checks": [
            {
            "ID": "percona-server-84_check_script",
            "Interval": "3s",
            "Name": "Check for MySQL running on ${name}",
            "Notes": "Check for MySQL running on ${name}. Monitoring of MySQL metrics are enabled with this service.",
            "ServiceID": "percona-server-84_check_script",
            "Success_before_passing": 3,
            "Timeout": "3s",
            "args": [ "bash", "/usr/local/bin/consul-check-mysql.sh" ]
            }
          ]
        }
      }
  - path: /etc/consul.d/process-exporter-check-http.json
    permissions: "0644"
    content: |
      {
        "service": {
          "address": "${fqdn}",
          "id": "process-exporter",
          "name": "process-exporter",
          "port": 9256,
          "tags": ["${name}"],
          "checks": [
            {
            "HTTP": "http://${fqdn}:9256/metrics",
            "ID": "process-exporter_check_http",
            "Interval": "3s",
            "Method": "GET",
            "Name": "Check for process-exporter using HTTP",
            "Notes": "Check for process-exporter using HTTP. Monitoring of per-process metrics are enabled with this service.",
            "ServiceID": "process-exporter_check_http",
            "Success_before_passing": 3,
            "Timeout": "5s"
            }
          ]
        }
      }
  - path: /usr/local/bin/waiter.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      # Script to do all the waiting
      # File contents will be downloaded from githubcontent.com
  - path: /root/.my.cnf
    content: |
      [client]
      user=root
      password="${mysql_root_password}"

  - path: /etc/my.cnf.d/mysql_ps_84.cnf
    content: |
      [mysqld]

      # Host specific replication configuration
      #
      report_host = ${fqdn}
      report_port = 3306
      server_id   = 1${index}

      # Generic
      #
      datadir=/data
      socket=/var/lib/mysql/mysql.sock
      log-error=/var/log/mysqld.log
      pid-file=/var/run/mysqld/mysqld.pid
      log_error_verbosity=3
      log_error_suppression_list='MY-013360'
      loose-validate_password.policy=0
      percona_telemetry_disable=1

      # Configure binary logs
      #
      log-bin
      binlog_format=ROW
      binlog_expire_logs_seconds=86400
      binlog_space_limit=10G

      # Configure slow logs
      #
      slow_query_log=ON
      slow_query_log_always_write_time=1
      slow_query_log_use_global_control=all
      log_slow_rate_limit=2       # Log every other slow query
      log_slow_rate_type='query'
      log_slow_admin_statements=ON
      log_slow_replica_statements=ON
      log_slow_verbosity=full
      long_query_time=0

      # InnoDB
      #
      innodb_buffer_pool_size=1G
      innodb_flush_method=O_DIRECT

      # Configure statistics
      #
      userstat=ON
      performance_schema=ON
      innodb_monitor_enable=module_index

      # Async replication
      #
      gtid_mode=ON
      enforce_gtid_consistency=ON

  - path: /tmp/replica-config.cnf
    content: |
      [mysqld]
      innodb_flush_log_at_trx_commit=0
      innodb_flush_method=O_DIRECT
      innodb_flush_neighbors=0
      read_only=1
      replica_parallel_workers=6
      replica_preserve_commit_order=1
      sync_binlog=0

  - path: /root/init-mysql.sh
    content: |
      #!/bin/bash

      for (( i=1 ; i<=30 ; i++ )); do
        if [[ "$(grep "root@localhost:" /var/log/mysqld.log | tail -n1 | wc -l)" == "1" ]]; then
            MYSQL_ROOT_PASSWORD=$(grep "root@localhost:" /var/log/mysqld.log | tail -n1 | rev | cut -d' ' -f1 | rev)
            mysql --connect-expired-password -uroot -p"$MYSQL_ROOT_PASSWORD" -Bse "ALTER USER root@localhost IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;";
            break;
        else
            echo "retry";
            sleep 2;
        fi;
      done;

      if [ "${name}" == "percona-server-84-0" ]; then
        for (( i=1 ; i<=300 ; i++ )); do
            if $(mysql --defaults-file=/root/.my.cnf -Be "show variables where variable_name = 'version';" >/dev/null); then
              mysql --defaults-file=/root/.my.cnf -Be "SET GLOBAL validate_password.special_char_count = 0;";
              mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;CREATE USER 'pmm-admin'@'localhost' IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD, BACKUP_ADMIN ON *.* TO 'pmm-admin'@'localhost'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;CREATE USER 'consul-health-check'@'localhost' IDENTIFIED BY '${mysql_root_password}' WITH MAX_USER_CONNECTIONS 2; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;GRANT USAGE ON *.* TO 'consul-health-check'@'localhost'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE DATABASE IF NOT EXISTS sbtest;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE DATABASE IF NOT EXISTS sbtest_direct;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE DATABASE IF NOT EXISTS sbtest_proxysql;";
              mysql --defaults-file=/root/.my.cnf -Be "GRANT ALL PRIVILEGES ON sbtest.* TO 'pmm-admin'@'localhost'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE USER 'sysbench-direct-ps84'@'%' IDENTIFIED BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "GRANT ALL PRIVILEGES ON sbtest_direct.* TO 'sysbench-direct-ps84'@'%'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE USER 'sysbench-proxysql-ps84'@'%' IDENTIFIED BY '${mysql_sysbench_password}'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "GRANT ALL PRIVILEGES ON sbtest_proxysql.* TO 'sysbench-proxysql-ps84'@'%'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE USER replica@'%' IDENTIFIED BY '${mysql_replica_password}'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "GRANT REPLICATION SLAVE, CONNECTION_ADMIN, BACKUP_ADMIN, GROUP_REPLICATION_STREAM, REPLICATION CLIENT ON *.* TO replica@'%'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "CREATE USER proxysql@'%' IDENTIFIED BY '${proxysql_monitor_password}'; FLUSH PRIVILEGES;";
              mysql --defaults-file=/root/.my.cnf -Be "GRANT ALL PRIVILEGES ON *.* TO proxysql@'%'; FLUSH PRIVILEGES;";
              break;
            else
              echo "retry";
              sleep 3;
            fi;
        done;
      fi

      if [ "${name}" == "percona-server-84-1" ]; then
        for (( i=1 ; i<=300 ; i++ )); do
            if $(mysql --defaults-file=/root/.my.cnf -Be "show variables where variable_name = 'version';" >/dev/null); then
                # https://dev.mysql.com/doc/refman/8.0/en/change-replication-source-to.html
                mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;CREATE USER 'pmm-admin'@'localhost' IDENTIFIED BY '${mysql_root_password}'; FLUSH PRIVILEGES;";
                mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD, BACKUP_ADMIN ON *.* TO 'pmm-admin'@'localhost'; FLUSH PRIVILEGES;";
                mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;CREATE USER 'consul-health-check'@'localhost' IDENTIFIED BY '${mysql_root_password}' WITH MAX_USER_CONNECTIONS 2; FLUSH PRIVILEGES;";
                mysql --defaults-file=/root/.my.cnf -Be "SET SQL_LOG_BIN=0;GRANT USAGE ON *.* TO 'consul-health-check'@'localhost'; FLUSH PRIVILEGES;";
                mysql --defaults-file=/root/.my.cnf -Be "CHANGE REPLICATION SOURCE TO SOURCE_HOST='percona-server-84-0', SOURCE_PORT=3306, SOURCE_USER='replica', SOURCE_PASSWORD='${mysql_replica_password}', SOURCE_AUTO_POSITION=1, SOURCE_SSL=1;";
                mysql --defaults-file=/root/.my.cnf -Be "START REPLICA;";
                break;
            else
                echo "retry";
                sleep 3;
            fi;
        done;
      fi

  - path: /etc/logrotate.d/mysql
    permissions: "0644"
    content: |
      /var/log/mysqld.log {
          create 600 mysql mysql
          notifempty
          daily
          rotate 5
          size 5G
          missingok
          nocompress
        postrotate
          if test -x /usr/bin/mysqladmin && /usr/bin/mysqladmin ping &>/dev/null
          then
            /usr/bin/mysqladmin flush-logs
          fi
        endscript
      }
