#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

runcmd:
  - timeout 60 bash -c 'while [ -f /var/run/yum.pid ]; do echo "wait for yum to get unlocked..."; sleep 5; done'
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install consul
  - systemctl enable consul
  - systemctl start consul
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release enable tools release
  - yum -y install pmm2-client sysbench
  - mkdir -p /etc/sysbench
  - chmod +x /etc/sysbench/exec_sysbench.sh
  - systemctl enable sysbench.ps.mysql80
  - systemctl enable sysbench.ps.pxc80
  - systemctl enable sysbench.proxysql_ps
  - systemctl enable sysbench.proxysql_pxc
  - systemctl enable sysbench.ps.pg13
  - systemctl start sysbench.ps.mysql80
  - systemctl start sysbench.ps.pxc80
  - systemctl start sysbench.proxysql_ps
  - systemctl start sysbench.proxysql_pxc
  - systemctl start sysbench.ps.pg13
  - timeout 120 bash -c 'until curl --request 'GET' --insecure https://${pmm_server_endpoint}/v1/readyz ; do sleep 3; done'
  - pmm-admin config --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_admin_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - systemctl list-units sysbench.*.service | sed -E '1d;/^LOAD/,$d;s/ .*//g' > sysbench.services.txt
  - yum -y install http://yum.puppet.com/puppet8-release-el-7.noarch.rpm
  - yum -y install puppet-agent
  - source /etc/profile.d/puppet-agent.sh ; puppet config set server ${pmm_server_host} --section main
  - source /etc/profile.d/puppet-agent.sh ; puppet config set fact_value_length_soft_limit 16384 --section main
  - source /etc/profile.d/puppet-agent.sh ; puppet ssl bootstrap
  - source /etc/profile.d/puppet-agent.sh ; puppet resource service puppet ensure=running enable=true
  - source /etc/profile.d/puppet-agent.sh ; puppet agent --test

write_files:
  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      bootstrap_expect=3
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "proxysql"]
      server = true
      ui_config{
        enabled = true
      }
  - path: /etc/sysbench/exec_sysbench.sh
    content: |
      #!/bin/bash

      SYSBENCH_CFG="$${1}";
      if [[ "$${SYSBENCH_CFG}" == "" ]]; then
          exit 1;
      fi;

      OLTP_AVAILABLE=(oltp_delete.lua oltp_insert.lua oltp_point_select.lua oltp_read_only.lua oltp_read_write.lua oltp_update_index.lua oltp_update_non_index.lua oltp_write_only.lua)
      OLTP_PATH='/usr/share/sysbench'
      for (( ; ; )); do
          RND_OLTP_BENCH="$${OLTP_AVAILABLE[RANDOM%$${#OLTP_AVAILABLE[@]}]}";
          RND_NUM_THREADS="$(( $${RANDOM} % 17 + 8 ))";   # 8..24
          RND_EXEC_TIME="$(( $${RANDOM} % 300 + 600 ))";    # 600..900
          echo -e "\nRunning: $${RND_OLTP_BENCH} - $(date "+%Y-%m-%d / %H:%M:%S")\n=======================";
          pmm-admin annotate "${SYSBENCH_CFG} - $${RND_OLTP_BENCH}" --tags "${SYSBENCH_CFG},$${RND_OLTP_BENCH}"";
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" prepare;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" run;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
      done;

  - path: /etc/sysbench/percona-server-80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-server-80-0
      mysql-port=3306
      mysql-user=sysbench-direct-ps
      mysql-password=${mysql80_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0
      
  - path: /etc/sysbench/percona_xtradb_cluster_80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-xtradb-cluster-1
      mysql-port=3306
      mysql-user=sysbench-direct-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      tables=20

  - path: /etc/sysbench/percona-server-postgres-13.cnf
    content: |
      db-driver=pgsql
      pgsql-host=postgres-13
      pgsql-port=5432
      pgsql-user=sysbench
      pgsql-password=${postgres_sysbench_password}
      psql-db=sbtest
      rate=0
      report-interval=10
      verbosity=0

  - path: /etc/sysbench/proxysql_ps.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-ps
      mysql-password=${percona_server_80_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5

  - path: /etc/sysbench/proxysql_pxc.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5

  - path: /usr/lib/systemd/system/sysbench.ps80.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh percona-server-80.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.pxc80.service
    content: |
      [Unit]
      Description=Sysbench for PXC 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh percona_xtradb_cluster_80.cnf

      [Install]
      WantedBy=multi-user.target
     
  - path: /usr/lib/systemd/system/sysbench.proxysql_ps.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Server for MySQL
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_ps.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.proxysql_ps.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona XtraDB Cluster
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_pxc.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.postgres13.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server for PostgreSQL 13
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh percona-server-postgres-13.cnf

      [Install]
      WantedBy=multi-user.target
