#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

runcmd:
  - timeout 60 bash -c 'while [ -f /var/run/yum.pid ]; do echo "wait for yum to get unlocked..."; sleep 5; done'
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install consul
  - systemctl enable consul
  - systemctl start consul
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release enable tools release
  - yum -y install pmm2-client sysbench
  - percona-release enable mysql-shell
  - percona-release enable ps-80
  - yum -y install percona-mysql-shell
  - mkdir -p /etc/sysbench
  - chmod +x /etc/sysbench/exec_sysbench.sh
  - systemctl enable sysbench.ps80
  - systemctl enable sysbench.ps81
  - systemctl enable sysbench.pxc80
  - systemctl enable sysbench.proxysql_ps80
  - systemctl enable sysbench.proxysql_ps81
  - systemctl enable sysbench.proxysql_pxc80
  - systemctl enable sysbench.haproxy.pxc80
  - systemctl enable sysbench.postgres13
  - systemctl start sysbench.ps80
  - systemctl start sysbench.ps81
  - systemctl start sysbench.pxc80
  - systemctl start sysbench.proxysql_ps80
  - systemctl start sysbench.proxysql_ps81
  - systemctl start sysbench.proxysql_pxc80
  - systemctl start sysbench.haproxy.pxc80
  - systemctl start sysbench.postgres13
  - timeout 120 bash -c 'until curl --request 'GET' --insecure https://${pmm_server_endpoint}/v1/readyz ; do sleep 3; done'
  - pmm-admin config --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_admin_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - systemctl list-units sysbench.*.service | sed -E '1d;/^LOAD/,$d;s/ .*//g' > sysbench.services.txt

write_files:
  - path: /root/.mysqlsh/options.json
    permissions: "0644"
    content: |
      {
        "history.autoSave": "true"
      }
  - path: /root/.my.cnf
    content: |
      [client]
      user=root
      # Percona Server for MySQL 8.0
      password="${mysql80_sysbench_password}"
      # Percona Server for MySQL 8.1 
      password="${mysql81_sysbench_password}"
      # PXC 8
      password="${percona_xtradb_cluster_80_password}"
      
  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      bootstrap_expect=3
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "proxysql"]
      server = true
      ui_config{
        enabled = true
      }
  - path: /etc/sysbench/exec_sysbench.sh
    content: |
      #!/bin/bash

      SYSBENCH_CFG="$${1}";
      if [[ "$${SYSBENCH_CFG}" == "" ]]; then
          exit 1;
      fi;

      OLTP_AVAILABLE=(oltp_delete.lua oltp_insert.lua oltp_point_select.lua oltp_read_only.lua oltp_read_write.lua oltp_update_index.lua oltp_update_non_index.lua oltp_write_only.lua)
      OLTP_PATH='/usr/share/sysbench'
      for (( ; ; )); do
          RND_OLTP_BENCH="$${OLTP_AVAILABLE[RANDOM%$${#OLTP_AVAILABLE[@]}]}";
          RND_NUM_THREADS="$(( $${RANDOM} % 17 + 8 ))";   # 8..24
          RND_EXEC_TIME="$(( $${RANDOM} % 300 + 600 ))";    # 600..900
          echo -e "\nRunning: $${RND_OLTP_BENCH} - $(date "+%Y-%m-%d / %H:%M:%S")\n=======================";
          pmm-admin annotate "$${SYSBENCH_CFG} - $${RND_OLTP_BENCH}" --tags "$${SYSBENCH_CFG},$${RND_OLTP_BENCH}";
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" prepare;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" run;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
      done;

  - path: /etc/sysbench/ps80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-server-80-0
      mysql-port=3306
      mysql-user=sysbench-direct-ps
      mysql-password=${mysql80_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0

  - path: /etc/sysbench/ps81.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-server-81-0
      mysql-port=3306
      mysql-user=sysbench-direct-ps81
      mysql-password=${mysql81_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0

  - path: /etc/sysbench/pxc80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-xtradb-cluster-1
      mysql-port=3306
      mysql-user=sysbench-direct-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      tables=20

  - path: /etc/sysbench/postgres13.cnf
    content: |
      db-driver=pgsql
      pgsql-host=postgres-13
      pgsql-port=5432
      pgsql-user=sysbench
      pgsql-password=${postgres_sysbench_password}
      psql-db=sbtest
      rate=0
      report-interval=10
      verbosity=0

  - path: /etc/sysbench/proxysql_ps80.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-ps
      mysql-password=${mysql80_sysbench_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5

  - path: /etc/sysbench/proxysql_ps81.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-ps81
      mysql-password=${mysql81_sysbench_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  
  - path: /etc/sysbench/proxysql_pxc80.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5

  - path: /etc/sysbench/haproxy_pxc80.cnf
    content: |
      mysql-db=sbtest_haproxy
      mysql-host=haproxy
      mysql-port=3306
      mysql-user=sysbench-haproxy-pxc
      mysql-password=BPwe4foqoGP9zTHSNUYbcAouSg4QfO
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5

  - path: /usr/lib/systemd/system/sysbench.ps80.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh ps80.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.ps81.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server 8.1
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh ps81.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.pxc80.service
    content: |
      [Unit]
      Description=Sysbench for PXC 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh pxc80.cnf

      [Install]
      WantedBy=multi-user.target
     
  - path: /usr/lib/systemd/system/sysbench.proxysql_ps80.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Server for MySQL
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_ps80.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.proxysql_ps81.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Server for MySQL 8.1
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_ps81.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.proxysql_pxc80.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona XtraDB Cluster
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_pxc80.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.postgres13.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server for PostgreSQL 13
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh postgres13.cnf

      [Install]
      WantedBy=multi-user.target

  - path: /usr/lib/systemd/system/sysbench.haproxy.pxc80.service
    content: |
      [Unit]
      Description=Sysbench for PXC 8 behind HAProxy
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh haproxy_pxc80.cnf

      [Install]
      WantedBy=multi-user.target
