#cloud-config
fqdn: ${fqdn}
hostname: ${name}
manage_etc_hosts: true
prefer_fqdn_over_hostname: true
preserve_hostname: false
repo_upgrade: all

packages:
  - nmap-ncat
  - jq
  - curl

runcmd:
  - timeout 60 bash -c 'while [ -f /var/run/yum.pid ]; do echo "wait for yum to get unlocked..."; sleep 5; done'
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install consul
  - systemctl enable consul
  - systemctl start consul
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release enable-only ps-80
  - yum -y install percona-server-client
  - percona-release enable tools release
  - yum -y install pmm2-client sysbench
  - percona-release enable mysql-shell
  - yum -y install percona-mysql-shell
  - mkdir -p /etc/sysbench
  - chmod +x /etc/sysbench/exec_sysbench.sh
  - systemctl enable sysbench.ps80
  - systemctl enable sysbench.ps81
  - systemctl enable sysbench.pxc80
  - systemctl enable sysbench.pgr81
  - systemctl enable sysbench.oracle_mysql83
  - systemctl enable sysbench.proxysql_ps80
  - systemctl enable sysbench.proxysql_ps81
  - systemctl enable sysbench.proxysql_pxc80
  - systemctl enable sysbench.proxysql_pgr81
  - systemctl enable sysbench.haproxy.pxc80
  - systemctl enable sysbench.haproxy.pgr81
  - systemctl enable sysbench.postgres13
  - systemctl start sysbench.ps80
  - systemctl start sysbench.ps81
  - systemctl start sysbench.pxc80
  - systemctl start sysbench.pgr81
  - systemctl start sysbench.proxysql_ps80
  - systemctl start sysbench.proxysql_ps81
  - systemctl start sysbench.proxysql_pxc80
  - systemctl start sysbench.proxysql_pgr81
  - systemctl start sysbench.oracle_mysql83
  - systemctl start sysbench.haproxy.pxc80
  - systemctl start sysbench.haproxy.pgr81
  - systemctl start sysbench.postgres13
  - bash /usr/local/bin/waiter.sh readyz
  - pmm-admin config --az="us-east-1f" --region="us-east-1" --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_admin_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - systemctl list-units sysbench.*.service | sed -E '1d;/^LOAD/,$d;s/ .*//g' > sysbench.services.txt
  - wget --quiet https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter_0.7.10_linux_386.rpm
  - yum -y install process-exporter_0.7.10_linux_386.rpm
  - service process-exporter start
  - bash /usr/local/bin/waiter.sh process-exporter
  - pmm-admin add external --group=processes --listen-port=9256 --environment="prod" --service-name="${name}-processes" --cluster="processes-cluster"

write_files:
  - path: /etc/resolv.conf
    permissions: "0644"
    content: |
      ; generated by #cloud-config
      search ${local_domain} ec2.internal
      options timeout:2 attempts:5
      nameserver 10.0.0.2
  - path: /root/.mysqlsh/options.json
    permissions: "0644"
    content: |
      {
        "history.autoSave": "true"
      }
  - path: /root/.my.cnf
    content: |
      [client]
      user=root
  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      bootstrap_expect=3
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "bastion"]
      server = true
      ui_config{
        enabled = true
      }
  - path: /etc/consul.d/process-exporter-check-http.json
    permissions: "0644"
    content: |
      {
        "service": {
          "address": "${fqdn}",
          "id": "process-exporter",
          "name": "process-exporter",
          "port": 9256,
          "tags": ["${name}"],
          "checks": [
            {
            "HTTP": "http://${fqdn}:9256/metrics",
            "ID": "process-exporter_check_http",
            "Interval": "3s",
            "Method": "GET",
            "Name": "Check for process-exporter using HTTP",
            "Notes": "Check for process-exporter using HTTP. Monitoring of per-process metrics are enabled with this service.",
            "ServiceID": "process-exporter_check_http",
            "Success_before_passing": 3,
            "Timeout": "5s"
            }
          ]
        }
      }
  - path: /usr/local/bin/waiter.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      # Script to do all the waiting
      service="$1"
      if [[ $service == "process-exporter" ]]; then
        # process-exporter
        while true; do
          # Get the status of the process-exporter_check_http check
          status=$(dig @127.0.0.1 -p 8600 ${name}.process-exporter.service.consul SRV | awk '/SRV.*${fqdn}\.$/ {print $1}')

          if [[ $status == "${name}.process-exporter.service.consul." ]]; then
            echo "process-exporter check is passing."
            exit 0
          fi

          # If the check is not passing, wait for a short interval and try again
          echo "process-exporter check is not passing. Will retry in 3 seconds..."
          sleep 3
        done
      elif [[ $service == "readyz" ]] ; then
        while true; do
          dnsstatus=$(dig pmm-server.${environment_name}.local A | awk '/A.*10.*$/ {print $1}')
          if [[ $dnsstatus == "pmm-server.${environment_name}.local." ]]; then
            echo "PMMreadyz_check_http DNS check is passing."
            status=$(dig @127.0.0.1 -p 8600 pmmreadyz.service.consul SRV | awk '/SRV.*bastion.${environment_name}.local.$/ {print $1}')
            if [[ $status == "pmmreadyz.service.consul." ]]; then
              echo "PMMreadyz_check_http check is passing."
              exit 0  
            fi
          else
            echo "PMMreadyz_check_http DNS check is not passing."
          fi
          echo "PMMreadyz_check_http check is not passing. Will retry in 1 second..."
          sleep 1
        done
      fi
  - path: /etc/sysbench/exec_sysbench.sh
    content: |
      #!/bin/bash
      SYSBENCH_CFG="$${1}";
      if [[ "$${SYSBENCH_CFG}" == "" ]]; then
          exit 1;
      fi;
      check_failure() {
          if [ $? -ne 0 ]; then
            echo "Seems to be a problem with the endpoint. Sleeping so we don't spam the annotations!";
            sleep 60;
          fi
      }  
      OLTP_AVAILABLE=(oltp_delete.lua oltp_insert.lua oltp_point_select.lua oltp_read_only.lua oltp_read_write.lua oltp_update_index.lua oltp_update_non_index.lua oltp_write_only.lua)
      OLTP_PATH='/usr/share/sysbench'
      for (( ; ; )); do
          RND_OLTP_BENCH="$${OLTP_AVAILABLE[RANDOM%$${#OLTP_AVAILABLE[@]}]}";
          RND_NUM_THREADS="$(( $${RANDOM} % 17 + 8 ))";   # 8..24
          RND_EXEC_TIME="$(( $${RANDOM} % 14400 + 14400 ))";    # 4 hours and up to 8 hours
          echo -e "\nRunning: $${RND_OLTP_BENCH} - $(date "+%Y-%m-%d / %H:%M:%S")\n=======================";
          pmm-admin annotate "$${SYSBENCH_CFG} - $${RND_OLTP_BENCH}" --tags "$${SYSBENCH_CFG},$${RND_OLTP_BENCH}";
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
          check_failure;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" prepare;
          check_failure;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" run;
          check_failure;
          sysbench --config-file=/etc/sysbench/"$${SYSBENCH_CFG}" --threads="$${RND_NUM_THREADS}" --time="$${RND_EXEC_TIME}" "$${OLTP_PATH}/$${RND_OLTP_BENCH}" cleanup;
          check_failure;
      done;
  - path: /etc/sysbench/pgr81.cnf
    content: |
      mysql-db=sbtest_direct_gr
      mysql-host=percona-group-replication-1
      mysql-port=3306
      mysql-user=sysbench-direct-percona-gr
      mysql-password=${percona_group_replication_81_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0
  - path: /etc/sysbench/ps80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-server-80-0
      mysql-port=3306
      mysql-user=sysbench-direct-ps
      mysql-password=${mysql80_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0
  - path: /etc/sysbench/ps81.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-server-81-0
      mysql-port=3306
      mysql-user=sysbench-direct-ps81
      mysql-password=${mysql81_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0
  - path: /etc/sysbench/oracle_mysql_83.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=oracle-mysql-83-0
      mysql-port=3306
      mysql-user=sysbench-direct-oracle-mysql-83
      mysql-password=${oracle_mysql_83_sysbench_password}
      rate=0
      report-interval=10
      table-size=1000000
      tables=20
      verbosity=0
  - path: /etc/sysbench/pxc80.cnf
    content: |
      mysql-db=sbtest_direct
      mysql-host=percona-xtradb-cluster-1
      mysql-port=3306
      mysql-user=sysbench-direct-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      tables=20
  - path: /etc/sysbench/postgresql13.cnf
    content: |
      db-driver=pgsql
      pgsql-host=postgresql-13
      pgsql-port=5432
      pgsql-user=sysbench
      pgsql-password=${postgres_sysbench_password}
      psql-db=sbtest
      rate=0
      report-interval=10
      verbosity=0
  - path: /etc/sysbench/proxysql_pgr81.cnf
    content: |
      mysql-db=sbtest_proxysql_gr
      mysql-host=proxysql
      mysql-port=3306
      mysql-user="sysbench-proxysql-percona-gr"
      mysql-password=${percona_group_replication_81_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /etc/sysbench/proxysql_ps80.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-ps
      mysql-password=${mysql80_sysbench_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /etc/sysbench/proxysql_ps81.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-ps81
      mysql-password=${mysql81_sysbench_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /etc/sysbench/proxysql_pxc80.cnf
    content: |
      mysql-db=sbtest_proxysql
      mysql-host=proxysql
      mysql-port=3306
      mysql-user=sysbench-proxysql-pxc
      mysql-password=${percona_xtradb_cluster_80_password}
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /etc/sysbench/haproxy_pgr81.cnf
    content: |
      mysql-db=sbtest_haproxy_gr
      mysql-host=haproxy
      mysql-port=33061
      mysql-user=sysbench-haproxy-percona-gr
      mysql-password=$(percona_group_replication_81_password)
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /etc/sysbench/haproxy_pxc80.cnf
    content: |
      mysql-db=sbtest_haproxy
      mysql-host=haproxy
      mysql-port=3306
      mysql-user=sysbench-haproxy-pxc
      mysql-password=BPwe4foqoGP9zTHSNUYbcAouSg4QfO
      events=0
      rand-type=pareto
      rate=0
      report-interval=10
      table_size=1000000
      time=0
      threads=5
  - path: /usr/lib/systemd/system/sysbench.pgr81.service
    content: |
      [Unit]
      Description=Sysbench for Percona Group Replication 8.1
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh pgr81.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.ps80.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh ps80.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.ps81.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server 8.1
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh ps81.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.oracle_mysql83.service
    content: |
      [Unit]
      Description=Sysbench for Oracle MySQL 8.3
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh oracle_mysql_83.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.pxc80.service
    content: |
      [Unit]
      Description=Sysbench for PXC 8
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh pxc80.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.proxysql_pgr81.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Group Replication 81.
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_pgr81.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.proxysql_ps80.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Server for MySQL
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_ps80.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.proxysql_ps81.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona Server for MySQL 8.1
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_ps81.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.proxysql_pxc80.service
    content: |
      [Unit]
      Description=Sysbench for ProxySQL against Percona XtraDB Cluster
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh proxysql_pxc80.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.postgres13.service
    content: |
      [Unit]
      Description=Sysbench for Percona Server for PostgreSQL 13
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh postgres13.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.haproxy.pgr81.service
    content: |
      [Unit]
      Description=Sysbench for Percona Group Replication 8.1 behind HAProxy
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh haproxy_pgr81.cnf

      [Install]
      WantedBy=multi-user.target
  - path: /usr/lib/systemd/system/sysbench.haproxy.pxc80.service
    content: |
      [Unit]
      Description=Sysbench for PXC 8 behind HAProxy
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=600
      ExecStart=/etc/sysbench/exec_sysbench.sh haproxy_pxc80.cnf

      [Install]
      WantedBy=multi-user.target
