#cloud-config
preserve_hostname: false
hostname: ${name}
fqdn: ${fqdn}
manage_etc_hosts: true
repo_upgrade: all

packages:
  - curl
  - jq

runcmd:
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install consul
  - systemctl enable consul
  - systemctl start consul
  - yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - percona-release setup -y pmm2-client
  - yum -y install pmm2-client
  - bash /tmp/pmm-server-waiter.sh
  - pmm-admin config --metrics-mode=push --force --server-insecure-tls --server-url='https://admin:${pmm_admin_password}@${pmm_server_endpoint}' ${fqdn} generic ${name}
  - percona-release setup -y psmdb-60
  - yum -y install python2 java-1.8.0-openjdk percona-server-mongodb
  - mkdir -p /data
  - curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz
  - tar xfz ycsb-0.17.0.tar.gz && rm ycsb-0.17.0.tar.gz
  - ln /root/ycsb-0.17.0/bin/ycsb /usr/local/sbin
  - /bin/bash /etc/ycsb/initial_load.sh
  - systemctl enable ycsb.mongodb60
  - systemctl start ycsb.mongodb60
  - wget https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter_0.7.10_linux_386.rpm
  - yum -y install process-exporter_0.7.10_linux_386.rpm
  - service process-exporter start
  - pmm-admin add external --group=processes --listen-port=9256 --environment="${environment_name}" --service-name="${name}-processes"

write_files:

  - path: /etc/consul.d/consul.hcl
    permissions: "0644"
    content: |
      bind_addr = "0.0.0.0"
      client_addr = "0.0.0.0"
      data_dir = "/opt/consul"
      enable_local_script_checks = true
      node_name="${name}"
      retry_join = ["pmm-server", "sysbench", "proxysql"]
      server = false
      ui_config{
        enabled = true
      }
  - path: /tmp/pmm-server-waiter.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      while true; do
      # Get the status of the PMMreadyz_check_http check
      status=$(dig @127.0.0.1 -p 8600 pmmreadyz.service.consul SRV  | grep pmm-server | awk '/A/ {print $1}')
      
      if [[ $status == "pmm-server.node.dc1.consul." ]]; then
        echo "PMMreadyz_check_http check is passing."
        exit 0
      fi

      # If the check is not passing, wait for a short interval and try again
      echo "PMMreadyz_check_http check is not passing. Will retry in 5 seconds..."
      sleep 5
      done
  - path: /etc/ycsb/shard.js
    content: |
      sh.enableSharding('ycsb');
      sh.shardCollection('ycsb.usertable', { "_id" : "hashed" }, false, { numInitialChunks : 20 });

  - path: /etc/ycsb/initial_load.sh
    permissions: "0744"
    content: |
      #!/bin/bash
      
      # Wait for mongos
      echo "-- Waiting for all 9 mongo servers..."
      
      for (( i=1 ; i<=100 ; i++ )); do
        s=$(curl -s --get http://pmm-server:8500/v1/catalog/service/mongo | jq 'length')
        
        if [ $s -eq 9 ]; then
          echo "-- Looks like all 9 mongos are online"
          break
        fi
        
        echo "-- Only $${s} mongos responding to ping; retry $${i}/100"
        sleep 2
      done
      
      # All 9 mongos online, connect to mongos-0 and configure sharding
      mongosh --port 27019 --host mongo-60-mongos-0 -u ycsb -p '${mongodb_ycsb_password}' /etc/ycsb/shard.js
      sleep 2
      
      # Prepare the benchmarking dataset
      /root/ycsb-0.17.0/bin/ycsb load mongodb -P /root/ycsb-0.17.0/workloads/workloadb -threads 4 -p recordcount=100000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"

  - path: /etc/ycsb/exec_ycsb.sh
    permissions: "0744"
    content: |
      #!/bin/bash

      while true; do
        /root/ycsb-0.17.0/bin/ycsb run mongodb -s -P /root/ycsb-0.17.0/workloads/workloada -threads 4 -p recordcount=100000 -p operationcount=1000000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"
        sleep 10s
        /root/ycsb-0.17.0/bin/ycsb run mongodb -s -P /root/ycsb-0.17.0/workloads/workloadb -threads 4 -p recordcount=100000 -p operationcount=1000000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"
        sleep 5s
        /root/ycsb-0.17.0/bin/ycsb run mongodb -s -P /root/ycsb-0.17.0/workloads/workloadc -threads 4 -p recordcount=100000 -p operationcount=1000000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"
        sleep 10s
        /root/ycsb-0.17.0/bin/ycsb run mongodb -s -P /root/ycsb-0.17.0/workloads/workloade -threads 4 -p recordcount=100000 -p operationcount=1000000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"
        sleep 5s
        /root/ycsb-0.17.0/bin/ycsb run mongodb -s -P /root/ycsb-0.17.0/workloads/workloadf -threads 4 -p recordcount=100000 -p operationcount=1000000 -p mongodb.url="mongodb://ycsb:${mongodb_ycsb_password}@mongo-60-mongos-0:27019/"
        sleep 5s
      done

  - path: /usr/lib/systemd/system/ycsb.mongodb60.service
    content: |
      [Unit]
      Description=YCSB for MongoDB 6.0
      After=network.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=10
      ExecStart=/etc/ycsb/exec_ycsb.sh

      [Install]
      WantedBy=multi-user.target
